modLoader = "javafml"
loaderVersion = "[${forgeFMLVersion},)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejsVersion},)"
ordering = "NONE"
side = "BOTH"
