
modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPLv3"

[[mods]]
modId = "lootjs"
version = "${file.jarVersion}"
displayName = "LootJS"
logoFile = "lootjs.png"
authors = "Lytho" #optional
description = '''
Modify global loot drops through kubejs
'''

[[dependencies.lootjs]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lootjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lootjs]]
modId = "kubejs"
mandatory = true
versionRange = "[1605.3.18-build.154,)"
ordering = "AFTER"
side = "BOTH"
