name: Release

on:
  workflow_dispatch:
    inputs:
      target_version:
        type: string
        required: false
        description: "mod version | empty = next option"
      update_type:
        type: choice
        required: false
        description: "update type"
        default: "minor"
        options:
          - "major"
          - "minor"
          - "patch"
          - "none"
      release_type:
        type: choice
        required: true
        description: "type of release"
        default: "release"
        options:
          - "alpha"
          - "beta"
          - "release"
      debug:
        type: boolean
        required: false
        default: false
        description: "enable debug mode (GitHub only)"

jobs:
  redirect:
    uses: AlmostReliable/.github/.github/workflows/release-nf.yml@main
    secrets: inherit
    with:
      java-distribution: "microsoft"
      java-version: "21"
      mod_name: "LootJS"
      curseforge_id: "570630"
      modrinth_id: "fJFETWDN"
      dependencies: |
        kubejs(required){curseforge:238086}{modrinth:umyGl7zF}
      target_version: ${{ github.event.inputs.target_version }}
      update_type: ${{ github.event.inputs.update_type }}
      release_type: ${{ github.event.inputs.release_type }}
      loaders: "neoforge"
      debug: ${{ github.event.inputs.debug }}
